export const THEMES = {
  mint: {
    '--color-primary': '#8ecfbe',
    '--color-secondary': '#e8f7f3',
    '--color-accent': '#f4a8a0',
    '--color-bg': '#f5fbf9',
    '--color-white': '#ffffff',
    '--color-text': '#2d3d38',
    '--color-text-light': '#5a8a78',
    '--topbar-bg': '#8ecfbe',
    '--title-grad-start': '#5aab94',
    '--title-grad-end': '#e08888',
    '--color-urgency-low': '#f0b429',
    '--color-urgency-mid': '#e07a30',
    '--color-urgency-high': '#e03030',
    '--color-urgency-bg-low': '#fffbef',
    '--color-urgency-bg-mid': '#fff5ee',
    '--color-urgency-bg-high': '#fff0f0',
  },
  peach: {
    '--color-primary': '#e8986c',
    '--color-secondary': '#fdeee0',
    '--color-accent': '#9b8ec4',
    '--color-bg': '#fffaf7',
    '--color-white': '#ffffff',
    '--color-text': '#3d2e24',
    '--color-text-light': '#a07858',
    '--topbar-bg': '#e8986c',
    '--title-grad-start': '#c07040',
    '--title-grad-end': '#9b8ec4',
    '--color-urgency-low': '#f0b429',
    '--color-urgency-mid': '#e07a30',
    '--color-urgency-high': '#e03030',
    '--color-urgency-bg-low': '#fffbef',
    '--color-urgency-bg-mid': '#fff5ee',
    '--color-urgency-bg-high': '#fff0f0',
  },
  rose: {
    '--color-primary': '#d4849a',
    '--color-secondary': '#faeef1',
    '--color-accent': '#7ba7bc',
    '--color-bg': '#fdf5f7',
    '--color-white': '#ffffff',
    '--color-text': '#3d2430',
    '--color-text-light': '#a06878',
    '--topbar-bg': '#d4849a',
    '--title-grad-start': '#b05870',
    '--title-grad-end': '#7ba7bc',
    '--color-urgency-low': '#f0b429',
    '--color-urgency-mid': '#e07a30',
    '--color-urgency-high': '#e03030',
    '--color-urgency-bg-low': '#fffbef',
    '--color-urgency-bg-mid': '#fff5ee',
    '--color-urgency-bg-high': '#fff0f0',
  },
  ocean: {
    '--color-primary': '#7ba7bc',
    '--color-secondary': '#dce8ef',
    '--color-accent': '#e07b6a',
    '--color-bg': '#f0f4f7',
    '--color-white': '#ffffff',
    '--color-text': '#2c3e50',
    '--color-text-light': '#5a7a8a',
    '--topbar-bg': '#7ba7bc',
    '--title-grad-start': '#4a7a8a',
    '--title-grad-end': '#e07b6a',
    '--color-urgency-low': '#f0b429',
    '--color-urgency-mid': '#e07a30',
    '--color-urgency-high': '#e03030',
    '--color-urgency-bg-low': '#fffbef',
    '--color-urgency-bg-mid': '#fff5ee',
    '--color-urgency-bg-high': '#fff0f0',
  },
  lavender: {
    '--color-primary': '#9b8ec4',
    '--color-secondary': '#ece8f5',
    '--color-accent': '#e8a87c',
    '--color-bg': '#f7f5fb',
    '--color-white': '#ffffff',
    '--color-text': '#2d2b3d',
    '--color-text-light': '#7a6aaa',
    '--topbar-bg': '#9b8ec4',
    '--title-grad-start': '#6a5a9a',
    '--title-grad-end': '#e8a87c',
    '--color-urgency-low': '#f0b429',
    '--color-urgency-mid': '#e07a30',
    '--color-urgency-high': '#e03030',
    '--color-urgency-bg-low': '#fffbef',
    '--color-urgency-bg-mid': '#fff5ee',
    '--color-urgency-bg-high': '#fff0f0',
  },
  ivory: {
    '--color-primary': '#a89880',
    '--color-secondary': '#ededea',
    '--color-accent': '#c4a882',
    '--color-bg': '#f8f8f5',
    '--color-white': '#ffffff',
    '--color-text': '#3a3630',
    '--color-text-light': '#8a8478',
    '--topbar-bg': '#e8e6e0',
    '--title-grad-start': '#a89880',
    '--title-grad-end': '#c4a882',
    '--color-urgency-low': '#f0b429',
    '--color-urgency-mid': '#e07a30',
    '--color-urgency-high': '#e03030',
    '--color-urgency-bg-low': '#fffbef',
    '--color-urgency-bg-mid': '#fff5ee',
    '--color-urgency-bg-high': '#fff0f0',
  },
  sky: {
    '--color-primary': '#8ec4e0',
    '--color-secondary': '#e0f0f8',
    '--color-accent': '#f4a8c0',
    '--color-bg': '#f2f8fc',
    '--color-white': '#ffffff',
    '--color-text': '#1c3040',
    '--color-text-light': '#5a80a0',
    '--topbar-bg': '#8ec4e0',
    '--title-grad-start': '#5a9ec0',
    '--title-grad-end': '#f4a8c0',
    '--color-urgency-low': '#f0b429',
    '--color-urgency-mid': '#e07a30',
    '--color-urgency-high': '#e03030',
    '--color-urgency-bg-low': '#fffbef',
    '--color-urgency-bg-mid': '#fff5ee',
    '--color-urgency-bg-high': '#fff0f0',
  },
  dark: {
    '--color-primary': '#4a9e8a',
    '--color-secondary': '#2a3442',
    '--color-accent': '#e07a7a',
    '--color-bg': '#1e2530',
    '--color-white': '#2a3442',
    '--color-text': '#e8edf3',
    '--color-text-light': '#a0b0c0',
    '--topbar-bg': '#1a2028',
    '--title-grad-start': '#4ac4a4',
    '--title-grad-end': '#e07a7a',
    '--color-urgency-low': '#f0b429',
    '--color-urgency-mid': '#e07a30',
    '--color-urgency-high': '#e03030',
    '--color-urgency-bg-low': '#2a2510',
    '--color-urgency-bg-mid': '#2a1a0a',
    '--color-urgency-bg-high': '#2a1010',
  },
}

export function applyTheme(theme) {
  const root = document.documentElement
  const vars = THEMES[theme]
  if (!vars) return
  Object.entries(vars).forEach(([key, val]) => {
    root.style.setProperty(key, val)
  })
}